# Generated by Django 5.1.7 on 2025-03-22 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmmodel',
            name='email',
        ),
        migrations.AddField(
            model_name='confirmmodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sms_code', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
