version: '3'
services:
  backend:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: 'postgres:14'
    env_file:
      - '.env'
    environment:
      POSTGRES_DB: '${NAME_DB}'
      POSTGRES_USER: '${USER_DB}'
      POSTGRES_PASSWORD: '${PASSWORD_DB}'
    volumes:
      - 'new-data:/var/lib/postgresql/data'
volumes:
  new-data: